# Generated by Django 3.0.8 on 2020-08-01 21:07

from django.db import migrations, models
import image_upload.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=False)),
                ('extended_image', models.ImageField(blank=True, null=True, upload_to=image_upload.models.extended_image_upload_path)),
                ('modified_image', models.ImageField(blank=True, null=True, upload_to=image_upload.models.modified_image_upload_path)),
            ],
        ),
    ]
